branch-defaults:
  default:
    environment: django-env
    group_suffix: null
  master:
    environment: django-env
global:
  application_name: Project-website
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
